# Generated by Django 4.2 on 2025-09-22 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(choices=[('Increase', 'Increase Balance'), ('Sale', 'Charge Sale')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency', models.CharField(max_length=150, unique=True)),
                ('balance_before', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
            ],
        ),
    ]
